'use client'

import { Provider } from "react-redux"
import { store } from "./store"
import { ToastContainer } from "react-toastify"
import { Vazirmatn } from 'next/font/google'
import '@/styles/globals.css'

const vazir = Vazirmatn({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <body className={vazir.className}>
                <Provider store={store}>
                    {children}
                    <ToastContainer />
                </Provider>
        </body>
    </html>
  )
}
